In [1]:
import numpy as np

In [21]:
a = np.zeros((5,4))

In [22]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
a.reshape(2, -1).shape

(2, 10)

In [28]:
np.expand_dims(a.reshape(2,-1), axis = 0)

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [31]:
a[1][2] = 1

In [32]:
np.argmax(a)

6

In [33]:
a

array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])